app: index.js

index.js: $(shell find src -type f | grep elm)  
	elm make src/Main.elm --output=index.js

launch:
	open http://localhost:8000/index.html
	cd build && elm reactor &

sa:
	killall elm || true
	open http://localhost:8000/src/${n}/Static/Standalone/${m}.elm && elm reactor
	#elm make src/Static/Standalone/${m}.elm --output=build/Standalone${m}.html
	#open build/Standalone${m}.html

stop:
	killall elm

# clean the javascript file generated by Elm
clean:
	rm build/index.js
	rm build/Standalone*.html

# clean the elm-stuff directory	
elmclean:
	rm -r elm-stuff/
